excluded:
  - coffee-hunter.xcodeproj
  - coffee-hunter/Preview Content

disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - multiline_parameters
  - vertical_whitespace_closing_braces

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

identifier_name:
  min_length: 2
  max_length: 40

type_name:
  min_length: 3
  max_length: 40
